[package]
name = "pirate_wars"
version = "0.1.0"
authors = ["DownTownScarf7 <vbence741@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
